version: '3.7'

services:

  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000

  db:
    container_name: db
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    volumes:
      - delivery_db:/var/lib/postgresql/data

volumes:
  delivery_db: {}
